manifest:
  defaults:
    revision: v0.3

  remotes:
    - name: MDStecker
      url-base: https://github.com/MDStecker
    - name: badjeff
      url-base: https://github.com/badjeff

  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml

    - name: zmk-analog-input-driver
      remote: MDStecker
      revision: main


  self:
    path: config