manifest:
  remotes:
    - name: github
      url-base: https://github.com

  projects:
    - name: zmk
      remote: github
      revision: main
      import: app/west.yml
      path: config

    - name: zmk-analog-input-driver
      remote: github
      revision: main
      path: modules/zmk/zmk-analog-input-driver

    
